#spring:
#  datasource:
#    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@aiclass_high?TNS_ADMIN=/Users/jongnyeonglee/Desktop/itAcademy/Spring/Wallet_aiclass
#    username: admin
#    password: Jjang0617!whdsud

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url:
      jdbc:oracle:thin:@db202202180852_high?TNS_ADMIN=C:/oracle/Wallet_DB202202180852
    username: admin
    password: Leaf950515!!


